Github Actions: update to nix-quick-install-action v30
Trying to solve this failure on Ubuntu runners:

    installing 'nix-2.12.0'
    error: cannot set loopback interface flags: Operation not permitted
    (use '--show-trace' to show detailed location information)
    Error: Process completed with exit code 1.