move rubocop-packaging checks to the top level
These were in a contrib subdirectory to avoid introducing a new
dependency on the rubocop-packaging gem. But the current layout doesn't
work on Github Actions. Bundler installs dependencies into
vendor/bundle/ and so Rubocop tries to check them and fails like this:

    [rubocop-packaging] Running RuboCop Packaging checks
    Error: The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`.
    (obsolete configuration found in /home/runner/work/sup/sup/vendor/bundle/ruby/3.0.0/gems/highline-2.0.3/.rubocop.yml, please update it)
    The `Style/MethodMissing` cop has been split into `Style/MethodMissingSuper` and `Style/MissingRespondToMissing`.
    (obsolete configuration found in /home/runner/work/sup/sup/vendor/bundle/ruby/3.0.0/gems/highline-2.0.3/.rubocop.yml, please update it)
    rubocop-packaging checks failed
    Error: Process completed with exit code 1.