tests: fix TestLineCursorMode failures due to Ncurses.tigetflag
The previous commit d21b4bebeb134b1cccefdb1c669542cc2d109b3e introduced
a call to Ncurses.tigetflag in BufferManager, but that method is only
defined after Ncurses.initscr or Ncurses.newterm have been called.

Fix TestLineCursorMode to initialise a dummy ncurses terminal on
/dev/null so that BufferManager can work in unit tests.

    TestLineCursorMode#test_jump_to_end:
    NoMethodError: undefined method `tigetflag' for Ncurses:Module

        @have_xterm_title = Ncurses.tigetflag("XT") > 0 || ENV["TERM"] =~ /(screen|tmux)/
                                   ^^^^^^^^^^
        lib/sup/buffer.rb:154:in `initialize'
        lib/sup/util.rb:594:in `new'
        lib/sup/util.rb:594:in `init'
        test/unit/test_line_cursor_mode.rb:13:in `setup'